#colores
set -g default-terminal "tmux-256color"
set-option -ga terminal-overrides ",xterm-256color:Tc"

#combinciones
set -g prefix C-a  #asignamos el nuevo
unbind C-b         #eliminamos el default
bind-key C-a send-prefix

#Horizontal
unbind %
bind u split-window -v -c "#{pane_current_path}"

#Vertical
unbind '"'
bind i split-window -h -c "#{pane_current_path}"

# open new window in the same directory of the current pane
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

#cerrar ventana

# floating window
bind-key -n M-g if-shell -F '#{==:#{session_name},scratch}' {
detach-client
} {
# open in the same directory of the current pane
display-popup -d "#{pane_current_path}" -E "tmux new-session -A -s scratch"
}

# Use xclip to copy and paste with the system clipboard
bind C-c run "tmux save-buffer - | xclip -i -sel clip"
bind C-v run "tmux set-buffer $(xclip -o -sel clip); tmux paste-buffer"

#asignar los numero de la ventana que comience directamente con 1
set -g base-index 1
# asignar los numero de los paneles que comience directamente con 1
set -g pane-base-index 1

# Modo vim
set -g mode-keys vi
if-shell 'uname | grep -q Darwin' 'bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"' 'bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "clip"'

#refrescar configuracion
unbind r
bind R source-file ~/.tmux.conf

#dimensionar las ventanas
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
set -g prefix C-a  #asignamos el nuevo
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5

#maximizar
bind -r m resize-pane -Z

# Mostrar la barra de estado arriba
set-option -g status-position top

#
set -g mouse on

set-window-option -g mode-keys vi

bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection

unbind -T copy-mode-vi MouseDragEnd1Pane

#plugins
#--------------------------------
set -g @plugin "tmux-plugins/tpm"
#--------------------------------
set -g @plugin "tmux-plugins/tmux-sensible"
#--------------------------------
set -g @plugin "christoomey/vim-tmux-navigator"
#-------------------------------
# barra de estado personalizada
# set -g @plugin "nordtheme/tmux"
#-------------------------------
set -g @plugin 'Nybkox/tmux-kanagawa'
set -g @kanagawa-theme 'Kanagawa'
set -g @kanagawa-plugins "git cpu-usage ram-usage"
set -g @kanagawa-ignore-window-colors true
#-------------------------------
# Tmux Resurrect - Para guardar sesiones y restaurarlas
set -g @plugin 'tmux-plugins/tmux-resurrect'
# Which Key - muestra un menú de atajos de teclado
set -g @plugin 'alexwforsythe/tmux-which-key'


run "~/.tmux/plugins/tpm/tpm"
